spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.120.171:3306/vehicle-info-management?useSSL=false&characterEncoding=utf-8
    username: root
    password: Hlxd@123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: com.yulj.common.core.dialect.MySQLDialectUTF8
      hibernate.format_sql: false
    open-in-view: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.18.120.171:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
xxl:
  job:
    admin:
      # xxl-job-admin 接口地址
      addresses: http://172.18.120.171:9080/xxl-job-admin
    executor:
      #通讯端口
      port: 9988
      appName: vehicle-management-service
logging:
  level:
    root: warn
    com.yulj: warn